# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1d22bd8940e0e7dc2831bd4579310ed"
name = "Spark Stock"
handle = "spark-stock"
application_url = "https://islamic-leads-outline-wide.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://islamic-leads-outline-wide.trycloudflare.com/auth/callback",
  "https://islamic-leads-outline-wide.trycloudflare.com/auth/shopify/callback",
  "https://islamic-leads-outline-wide.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
